import { create } from "zustand";

type Language = "en" | "sw";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatTsh: (v: number) => string;
}

const dict: Record<string, { en: string; sw: string }> = {
  dashboard: { en: "Dashboard", sw: "Dashibodi" },
  shops: { en: "Shops", sw: "Maduka" },
  inventory: { en: "Inventory", sw: "Stoo" },
  sales: { en: "Sales", sw: "Mauzo" },
  services: { en: "Services", sw: "Huduma" },
  reports: { en: "Reports", sw: "Ripoti" },
  users: { en: "Users", sw: "Watumiaji" },
  settings: { en: "Settings", sw: "Mipangilio" },
  notifications: { en: "Notifications", sw: "Taarifa" },
  "audit logs": { en: "Audit Logs", sw: "Kumbukumbu (Logs)" },
  "daily summary": { en: "Daily Summary", sw: "Ripoti ya Leo" },
  "active shop": { en: "Active Shop", sw: "Duka la Sasa" },
  logout: { en: "Logout", sw: "Toka" },
  help: { en: "Guide", sw: "Mwongozo" },
  "user guide": { en: "User Guide", sw: "Mwongozo wa Mtumiaji" },
  "user guide and manual": { en: "User Guide and System Manual", sw: "Mwongozo wa Mtumiaji na Maelekezo ya Mfumo" },
  "help_welcome": { en: "Welcome to the Shopix Management System manual. Learn how to manage your business efficiently.", sw: "Karibu kwenye mwongozo wa Mfumo wa Usimamizi wa Shopix. Jifunze jinsi ya kusimamia biashara yako kwa ufanisi." },
  "basics": { en: "Basics", sw: "Msingi" },
  "inventory_guide_title": { en: "Stock & Inventory Management", sw: "Usimamizi wa Bidhaa na Stoo" },
  "sales_debts_guide_title": { en: "Sales & Debts", sw: "Mauzo na Madeni" },
  "admin_guide_title": { en: "Administration", sw: "Usimamizi wa Mfumo" },
  "help_managing_shops": { en: "Managing Shops", sw: "Kusimamia Maduka" },
  "help_managing_shops_desc": { en: "The system supports multiple shops. Use the 'Shops' tab to add new locations, update shop names, or change categories. You can switch between shops using the selector in the top bar or on individual pages.", sw: "Mfumo unaruhusu maduka mengi. Tumia kichupo cha 'Maduka' kuongeza maeneo mapya, kubadili majina ya maduka, au kubadili aina za biashara. Unaweza kubadili duka kwa kutumia kiteuzi kilicho upande wa juu wa kioo au kwenye kurasa husika." },
  "help_navigation": { en: "Navigation", sw: "Urambazaji" },
  "help_navigation_desc": { en: "The sidebar allows you to access all main modules. If you are on a small screen, use the menu icon to toggle the sidebar. Use the top right language switcher to toggle between English and Swahili.", sw: "Upande wa kushoto unaruhusu kufungua sehemu zote kuu za mfumo. Kama unatumia kioo kidogo (simu), tumia alama ya mistari mitatu kufungua menyu hiyo. Tumia sehemu ya juu kulia kubadili lugha kati ya Kiingereza na Kiswahili." },
  "help_how_to_add_products": { en: "How to add new products?", sw: "Jinsi ya kuongeza bidhaa mpya?" },
  "help_how_to_add_products_desc": { en: "Go to the Inventory tab and click the '+ Add Product' button. Fill in the product name, buying cost, selling price, and initial quantity. You can also add expiry dates.", sw: "Nenda kwenye kichupo cha 'Stoo' na bonyeza kitufe cha '+ Ongeza Bidhaa'. Jaza jina la bidhaa, bei ya kununua, bei ya kuuza, na idadi ya mwanzo. Unaweza pia kuongeza tarehe ya mwisho ya matumizi." },
  "help_updating_stock": { en: "Updating stock (Restocking)", sw: "Kuongeza bidhaa (Restocking)" },
  "help_updating_stock_desc": { en: "To add quantity to an existing product, find the product in the table and click the 'Restock' button. Enter the amount to add.", sw: "Kuongeza idadi kwenye bidhaa iliyopo tayari, itafute bidhaa hiyo kwenye jedwali na bonyeza kitufe cha 'Ongeza Stoo'. Jaza kiasi unachotaka kuongeza." },
  "help_edit_delete": { en: "Editing and Deleting products", sw: "Kubadili na Kufuta bidhaa" },
  "help_edit_delete_desc": { en: "Click the three dots (⋮) icon in the actions column. Select 'Edit Details' to change prices or names, or 'Delete Item' to permanently remove it.", sw: "Bonyeza alama ya nukta tatu (⋮) kwenye safu ya vitendo. Chagua 'Badili Taarifa' kubadili bei au majina, au 'Futa Bidhaa' kuiondoa kabisa kwenye mfumo." },
  "help_recording_sales": { en: "Recording Sales", sw: "Kurekodi Mauzo" },
  "help_recording_sales_desc": { en: "In the Sales tab, use the search bar to find products. Enter the quantity sold and click 'Add to Receipt'. Once finished, click 'Complete Sale'.", sw: "Kwenye kichupo cha 'Mauzo', tumia sehemu ya utafutaji kupata bidhaa. Jaza idadi iliyouzwa na bonyeza 'Ongeza kwenye Risiti'. Ukimaliza, bonyeza 'Kamilisha Mauzo'." },
  "help_printing_services": { en: "Printing & Services", sw: "Uchapishaji na Huduma" },
  "help_printing_services_desc": { en: "Use the Services tab for non-product items like photocopying or custom services. These are recorded separately from physical inventory.", sw: "Tumia kichupo cha 'Huduma' kwa vitu ambavyo si bidhaa za dukani kama vile kutoa kopi (photocopy) au huduma nyinginezo. Hizi hurekodiwa tofauti na bidhaa za mwilini (stoo)." },
  "help_managing_debts": { en: "Managing Debts", sw: "Kusimamia Madeni" },
  "help_managing_debts_desc": { en: "The Debts tab tracks customers who buy on credit or installments. Record the customer name, phone, and balance. Use the 'Pay Installment' input in the debt card for payments. The card will show a green 'PAID' badge once the balance reaches zero.", sw: "Kichupo cha 'Madeni' hufuatilia wateja wanaonunua kwa mkopo au malipo ya awamu. Rekodi jina la mteja, simu, na deni analodaiwa. Tumia sehemu ya 'Lipa Awamu' kwenye kadi ya deni kurekodi malipo. Kadi itaonyesha alama ya kijani 'IMELIPWA' deni likiisha." },
  "help_user_mgmt": { en: "User Management", sw: "Usimamizi wa Watumiaji" },
  "help_user_mgmt_desc": { en: "Admins can manage staff accounts in the Users tab. You can assign specific permissions (e.g., only 'Sales Assistant' or 'Store Manager') to restrict access to sensitive features like reports or deleting stock.", sw: "Wasimamizi (Admins) wanaweza kusimamia akaunti za wafanyakazi kwenye kichupo cha 'Watumiaji'. Unaweza kugawa madaraka maalum (mfano: 'Sales Assistant' au 'Store Manager') kuzuia ufikiaji wa sehemu nyeti kama ripoti au kufuta bidhaa." },
  "help_reports_analytics": { en: "Reports & Analytics", sw: "Ripoti na Takwimu" },
  "help_reports_analytics_desc": { en: "Use the Reports tab to generate PDF or Excel summaries of your business. Filter by date, shop, or category to see your total earnings and stock value.", sw: "Tumia kichupo cha 'Ripoti' kutoa muhtasari wa biashara yako katika PDF au Excel. Unaweza kuchuja kwa tarehe, duka, au aina ya bidhaa kuona jumla ya mapato na thamani ya stoo." },
  "help_more_info": { en: "Need more help? Contact the system administrator.", sw: "Unahitaji msaada zaidi? Wasiliana na msimamizi wa mfumo." },
  "record_new_debt_tip": { en: "New Debt: Record the customer name, phone, and balance.", sw: "Deni Jipya: Rekodi jina la mteja, namba ya simu, na kiasi anachodaiwa." },
  "installment_tip": { en: "Installments: When a customer pays part of the debt, use the 'Pay Installment' input.", sw: "Malipo: Mteja akilipa sehemu ya deni, tumia sehemu ya 'Lipa Awamu' kurekodi kiasi hicho." },
  "debt_status_tip": { en: "Status: The card will show a green 'PAID' badge once the balance reaches zero.", sw: "Hali: Kadi itaonyesha rangi ya kijani pindi deni litakapokuwa limekamilika kulipwa." },
  debts: { en: "Debts / Borrowing", sw: "Madeni / Kukopa" },
  "all shops (admin)": { en: "All Shops (Admin)", sw: "Maduka Yote (Admin)" },
  "all my shops": { en: "All My Shops", sw: "Maduka Yangu Yote" },
  product: { en: "Product", sw: "Bidhaa" },
  price: { en: "Price", sw: "Bei" },
  quantity: { en: "Quantity", sw: "Idadi" },
  "total amount": { en: "Total Amount", sw: "Jumla" },
  "amount paid": { en: "Amount Paid", sw: "Kiasi Kilicholipwa" },
  balance: { en: "Balance", sw: "Baki" },
  customer: { en: "Customer", sw: "Mteja" },
  save: { en: "Save", sw: "Hifadhi" },
  cancel: { en: "Cancel", sw: "Ghairi" },
  action: { en: "Action", sw: "Kitendo" },
  actions: { en: "Actions", sw: "Vitendo" },
  "add new": { en: "Add New", sw: "Ongeza Mpya" },
  "search...": { en: "Search...", sw: "Tafuta..." },
  "add product": { en: "Add Product", sw: "Ongeza Bidhaa" },
  "restock items": { en: "Restock Items", sw: "Ongeza Stoo" },
  "quick restock": { en: "Quick Restock", sw: "Ongeza Haraka" },
  "edit details": { en: "Edit Details", sw: "Badili Taarifa" },
  "delete item": { en: "Delete Item", sw: "Futa Bidhaa" },
  "product name": { en: "Product Name", sw: "Jina la Bidhaa" },
  category: { en: "Category", sw: "Aina" },
  "buying cost": { en: "Buying Cost", sw: "Gharama ya Kununua" },
  "selling price": { en: "Selling Price", sw: "Bei ya Kuuza" },
  status: { en: "Status", sw: "Hali" },
  "record sale": { en: "Record Sale", sw: "Rekodi Mauzo" },
  "sale date": { en: "Sale Date", sw: "Tarehe ya Mauzo" },
  "total cost": { en: "Total Cost", sw: "Jumla ya Gharama" },
  profit: { en: "Profit", sw: "Faida" },
  date: { en: "Date", sw: "Tarehe" },
  time: { en: "Time", sw: "Muda" },
  name: { en: "Name", sw: "Jina" },
  location: { en: "Location", sw: "Eneo" },
  role: { en: "Role", sw: "Cheo" },
  email: { en: "Email", sw: "Barua Pepe" },
  "new shop": { en: "New Shop", sw: "Duka Jipya" },
  "add user": { en: "Add User", sw: "Ongeza Mtumiaji" },
  "system overview": { en: "System Overview", sw: "Muhtasari wa Mfumo" },
  "total products": { en: "Total Products", sw: "Jumla ya Bidhaa" },
  "total sales": { en: "Total Sales", sw: "Jumla ya Mauzo" },
  "total revenue": { en: "Total Revenue", sw: "Jumla ya Mapato" },
  "inventory value": { en: "Inventory Value", sw: "Thamani ya Stoo" },
  "est. profit": { en: "Est. Profit", sw: "Faida Inayokadiriwa" },
  "critical alerts": { en: "Critical Alerts", sw: "Taarifa Muhimu" },
  "today's sales": { en: "Today's Sales", sw: "Mauzo ya Leo" },
  "today's services": { en: "Today's Services", sw: "Huduma za Leo" },
  "active inventory": { en: "Active Inventory", sw: "Stoo Inayoendelea" },
  "urgent alerts": { en: "Urgent Alerts", sw: "Maonyo ya Haraka" },
  "today's top items": { en: "Today's Top Items", sw: "Bidhaa Zinazouza Sana Leo" },
  "no transactions yet today": { en: "No transactions yet today", sw: "Hakuna miamala leo" },
  "all systems normal": { en: "All systems normal", sw: "Hakuna tatizo lolote" },
  "only": { en: "Only", sw: "Zimebaki" },
  "remaining": { en: "remaining", sw: "tu" },
  "products": { en: "Products", sw: "Bidhaa" },
  "inventory health": { en: "Inventory Health", sw: "Hali ya Stoo" },
  "stock": { en: "Stock", sw: "Stoo" },
  "healthy": { en: "Healthy", sw: "Salama" },
  "low": { en: "Low", sw: "Chini" },
  "out": { en: "Out", sw: "Zimeisha" },
  "items": { en: "Items", sw: "Bidhaa" },
  "hello": { en: "Hello", sw: "Habari" },
  "urgent tasks": { en: "Urgent Tasks", sw: "Kazi za Haraka" },
  "service count": { en: "Service Count", sw: "Idadi ya Huduma" },
  "awaiting transactions": { en: "Awaiting Transactions", sw: "Inasubiri Miamala" },
  "view detailed report": { en: "View Detailed Report", sw: "Tazama Ripoti Kamili" },
  "revenue": { en: "Revenue", sw: "Mapato" },
  "top items": { en: "Top Items", sw: "Bidhaa Bora" },
  "no stock issues detected": { en: "No stock issues detected", sw: "Hakuna tatizo la stoo lililopatikana" },
  "systems online": { en: "Systems Online", sw: "Mifumo Ipo Sawa" },
  "admin session": { en: "Admin Session", sw: "Kipindi cha Admin" },
  "here is what is happening across your shops today.": { en: "Here is what is happening across your shops today.", sw: "Haya ndiyo yanayotokea kwenye maduka yako leo." },
  "operational control center": { en: "Operational Control Center", sw: "Kituo cha Udhibiti wa Uendeshaji" },
  "combined sales & service revenue": { en: "Combined sales & service revenue", sw: "Jumla ya mauzo na huduma" },
  "revenue sources": { en: "Revenue Sources", sw: "Vyanzo vya Mapato" },
  "contribution by type": { en: "Contribution by type", sw: "Mchango kwa aina" },
  "inventory pulse": { en: "Inventory Pulse", sw: "Hali ya Stoo" },
  "stock availability status": { en: "Stock availability status", sw: "Hali ya upatikanaji wa bidhaa" },
  "weekly performance": { en: "Weekly Performance", sw: "Uendeshaji wa Wiki" },
  "product sales": { en: "Product Sales", sw: "Mauzo ya Bidhaa" },
  "service revenue": { en: "Service Revenue", sw: "Mapato ya Huduma" },
  "weekly performance (sales vs services)": { en: "Weekly Performance (Sales vs Services)", sw: "Uendeshaji wa Wiki" },
  "revenue source (all time)": { en: "Revenue Source (All Time)", sw: "Vyanzo vya Mapato" },
  "low stock threshold warning": { en: "Low stock threshold is set to 10 units. Consider restocking items in the 'Low' and 'Out' categories immediately.", sw: "Kiwango cha chini kimewekwa kuwa bidhaa 10. Tafadhali ongeza bidhaa zilizo chini ya kiwango hicho." },
  "items needing attention": { en: "Items needing attention", sw: "Bidhaa zinazohitaji uangalizi" },
  "today's combined": { en: "Today's combined", sw: "Jumla ya leo" },
  "today's estimate": { en: "Today's estimate", sw: "Makadirio ya leo" },
  "product sales count": { en: "Product sales count", sw: "Idadi ya mauzo ya bidhaa" },
  "unique products": { en: "Unique products", sw: "Aina za bidhaa" },
  "performance overview for": { en: "Performance Overview for", sw: "Muhtasari wa utendaji wa" },
  "manage your products and track stock levels": { en: "Manage your products and track stock levels", sw: "Simamia bidhaa na kiasi kilichopo" },
  "track daily product sales and transactions": { en: "Track daily product sales and transactions", sw: "Fuatilia mauzo na miamala ya kila siku" },
  "manage borrowing and installments": { en: "Manage borrowing and installments", sw: "Simamia mikopo na malipo ya awamu" },
  "search borrower...": { en: "Search Borrower...", sw: "Tafuta Mkopaji..." },
  "issue debt": { en: "Issue Debt", sw: "Toa Mkopo" },
  "new borrowing": { en: "New Borrowing", sw: "Kukopa Kupya" },
  "borrower name": { en: "Borrower Name", sw: "Jina la Mkopaji" },
  "phone number": { en: "Phone Number", sw: "Namba ya Simu" },
  "optional": { en: "Optional", sw: "Sio Lazima" },
  "initial paid amount": { en: "Amount Paid (Initial)", sw: "Kiasi Alicholipia Awali" },
  "due date": { en: "Due Date", sw: "Tarehe ya Mwisho" },
  "create debt": { en: "Create Debt", sw: "Tengeneza Mkopo" },
  "loading debts...": { en: "Loading debts...", sw: "Inapakia mikopo..." },
  "no borrowings found": { en: "No borrowings found", sw: "Hakuna mikopo iliyopatikana" },
  "issued": { en: "Issued", sw: "Imetolewa" },
  "due": { en: "Due", sw: "Mwisho" },
  "total": { en: "Total", sw: "Jumla" },
  "paid": { en: "Paid", sw: "Imelipwa" },
  "pay installment": { en: "Pay Installment", sw: "Lipa Awamu" },
  "shop": { en: "Shop", sw: "Duka" },
  "operational summary": { en: "Operational Summary", sw: "Muhtasari wa Utendaji" },
  "daily business metrics and stock visibility": { en: "Daily business metrics and stock visibility", sw: "Takwimu za kila siku na mwonekano wa stoo" },
  "operational status": { en: "Operational Status", sw: "Hali ya Uendeshaji" },
  "monitoring data for": { en: "Monitoring data for", sw: "Kufuatilia data kuanzia" },
  "live data": { en: "LIVE DATA", sw: "DATA SAHIHI" },
  "today's revenue": { en: "Today's Revenue", sw: "Mapato ya Leo" },
  "view sales details": { en: "View Sales details", sw: "Tazama maelezo ya Mauzo" },
  "today's profit": { en: "Today's Profit", sw: "Faida ya Leo" },
  "view profit analysis": { en: "View profit analysis", sw: "Tazama uchambuzi wa faida" },
  "current stock (total)": { en: "Current Stock (Total)", sw: "Stoo Ilipo (Jumla)" },
  "units": { en: "Units", sw: "Vipande" },
  "manage inventory": { en: "Manage inventory", sw: "Simamia stoo" },
  "inventory cost": { en: "Inventory Cost", sw: "Gharama ya Stoo" },
  "full asset valuation": { en: "Full Asset Valuation", sw: "Tathmini ya rasilimali" },
  "stock health overview": { en: "Stock Health Overview", sw: "Hali ya Afya ya Stoo" },
  "stock utilization rate": { en: "Stock Utilization Rate", sw: "Kiwango cha Matumizi ya Stoo" },
  "items monitored": { en: "Items Monitored", sw: "Bidhaa Zinazofuatiliwa" },
  "low stock alerts": { en: "Low Stock Alerts", sw: "Taarifa za Uhaba wa Stoo" },
  "performance": { en: "Performance", sw: "Utendaji" },
  "target": { en: "Target", sw: "Lengo" },
  "currently performing at 85% of today's expected operational volume.": { en: "Currently performing at 85% of today's expected operational volume.", sw: "Kwa sasa inafanya kazi kwa 85% ya kiasi cha utendaji kinachotarajiwa leo." },
  "reports & analytics": { en: "Reports & Analytics", sw: "Ripoti na Kichanganuzi" },
  "comprehensive business insights and formatted exports": { en: "Comprehensive business insights and formatted exports", sw: "Uchambuzi kamili wa biashara na ripoti" },
  "to": { en: "to", sw: "hadi" },
  "select shop": { en: "Select Shop", sw: "Chagua Duka" },
  "all available shops": { en: "All Available Shops", sw: "Maduka Yote" },
  "daily sales report": { en: "Daily Sales Report", sw: "Ripoti ya Mauzo Kubwa" },
  "detailed breakdown of product sales by date and shop.": { en: "Detailed breakdown of product sales by date and shop.", sw: "Mchanganuo wa kina wa mauzo ya bidhaa kwa tarehe na duka." },
  "services report": { en: "Services Report", sw: "Ripoti ya Huduma" },
  "summary of all services (printing, photocopying, etc).": { en: "Summary of all services (printing, photocopying, etc).", sw: "Muhtasari wa huduma zote (kuchapa, kutoa nakala, n.k)." },
  "stock health report": { en: "Stock Health Report", sw: "Ripoti ya Hali ya Stoo" },
  "inventory levels, low stock alerts, and expiring items.": { en: "Inventory levels, low stock alerts, and expiring items.", sw: "Kiwango cha stoo, alerts za chini, na bidhaa zinazokaribia kuoza." },
  "profit & loss": { en: "Profit & Loss", sw: "Faida na Hasara" },
  "analysis of revenue, costs, and net margins.": { en: "Analysis of revenue, costs, and net margins.", sw: "Uchambuzi wa mapato, gharama, na faida halisi." },
  "generating...": { en: "Generating...", sw: "Inatengeneza..." },
  "excel export": { en: "Excel Export", sw: "Pakua Excel" },
  "creating...": { en: "Creating...", sw: "Inaunda..." },
  "pdf export": { en: "PDF Export", sw: "Pakua PDF" },
  "period revenue": { en: "Period Revenue", sw: "Mapato ya Kipindi" },
  "total profit": { en: "Total Profit", sw: "Jumla ya Faida" },
  "services cash": { en: "Services Cash", sw: "Pesa za Huduma" },
  "transactions": { en: "Transactions", sw: "Miamala" },
  "completed": { en: "Completed", sw: "Zimekamilika" },
  "asset value": { en: "Asset Value", sw: "Thamani ya Rasilimali" },
  "health alert": { en: "Health Alert", sw: "Onyo wa Hali" },
  "critical": { en: "Critical", sw: "Hatari" },
  "record new sale": { en: "Record New Sale", sw: "Rekodi Mauzo Mapya" },
  "in inventory": { en: "in inventory", sw: "stoo" },
  "adjust stock": { en: "Adjust Stock", sw: "Badili Kiasi" },
  "adjust inventory": { en: "Adjust Inventory", sw: "Badili Stoo" },
  "add, remove, or set exact stock levels": { en: "Add, remove, or set exact stock levels", sw: "Ongeza, ondoa au weka kiasi halisi" },
  "product to restock": { en: "Product to Restock", sw: "Bidhaa ya Kuongeza" },
  "type product name or batch number...": { en: "Type product name or batch number...", sw: "Andika jina la bidhaa au namba ya kundi..." },
  "no batch": { en: "No Batch", sw: "Hakuna Kundi" },
  "no matching products found": { en: "No matching products found", sw: "Hakuna bidhaa inayoendana iliyopatikana" },
  "change": { en: "Change", sw: "Badili" },
  "action type": { en: "Action Type", sw: "Aina ya Kitendo" },
  "add action": { en: "Add", sw: "Ongeza" },
  "remove action": { en: "Remove", sw: "Ondoa" },
  "set action": { en: "Set", sw: "Weka" },
  "e.g. 50": { en: "e.g. 50", sw: "Mf. 50" },
  "total after": { en: "Total after", sw: "Jumla baada ya" },
  "new batch number": { en: "New Batch Number", sw: "Namba Mpya ya Kundi" },
  "batch number": { en: "Batch Number", sw: "Namba ya Kundi" },
  "financial updates (optional)": { en: "Financial Updates (Optional)", sw: "Taarifa za Fedha (Sio Lazima)" },
  "new expiry date": { en: "New Expiry Date", sw: "Tarehe Mpya ya Kuisha Muda" },
  "updating...": { en: "Updating...", sw: "Inasisha..." },
  "confirm update": { en: "Confirm Update", sw: "Thibitisha" },
  "add service sale": { en: "Add Service Sale", sw: "Ongeza Mauzo ya Huduma" },
  "record service sale": { en: "Record Service Sale", sw: "Rekodi Mauzo ya Huduma" },
  "service name": { en: "Service Name", sw: "Jina la Huduma" },
  "price per unit": { en: "Price per Unit", sw: "Bei kwa Kipande" },
  "recording...": { en: "Recording...", sw: "Inarekodi..." },
  "record service": { en: "Record Service", sw: "Rekodi Huduma" },
  "edit": { en: "Edit", sw: "Badili" },
  "edit shop details": { en: "Edit Shop Details", sw: "Badili Taarifa za Duka" },
  "shop name": { en: "Shop Name", sw: "Jina la Duka" },
  "shop type": { en: "Shop Type", sw: "Aina ya Duka" },
  "saving...": { en: "Saving...", sw: "Inahifadhi..." },
  "save changes": { en: "Save Changes", sw: "Hifadhi Mabadiliko" },
  "create new shop": { en: "Create New Shop", sw: "Tengeneza Duka Jipya" },
  "create shop": { en: "Create Shop", sw: "Tengeneza Duka" },
  "select a shop first": { en: "Select a shop first", sw: "Chagua duka kwanza" },
  "no product found in this shop's inventory.": { en: "No product found in this shop's inventory.", sw: "Hakuna bidhaa iliyopatikana kwenye stoo ya duka hili." },
  "expiry date": { en: "Expiry date", sw: "Tarehe ya kuharibika" },
  "supplier": { en: "Supplier", sw: "Muzaji" },
  "manufacturer": { en: "Manufacturer", sw: "Mtengenezaji" },
  "adding...": { en: "Adding...", sw: "Inaongeza..." },
  "add new product": { en: "Add new product", sw: "Ongeza bidhaa mpya" },
  barcode: { en: "Barcode", sw: "Barcode" },
  "enter quantity": { en: "Enter quantity", sw: "Weka kiasi" },
  "unit price": { en: "Unit Price", sw: "Bei ya Kipande" },
  "total items": { en: "Total Items", sw: "Jumla ya Bidhaa" },
  "stock cost": { en: "Stock Cost", sw: "Gharama ya Stoo" },
  "est. revenue": { en: "Est. Revenue", sw: "Makadirio ya Mapato" },
  "current filtered stock": { en: "Current filtered stock", sw: "Stoo iliyochujwa sasa" },
  "investment in stock": { en: "Investment in stock", sw: "Uwekezaji kwenye stoo" },
  "full sale potential": { en: "Full sale potential", sw: "Uwezekano wa mauzo" },
  restock: { en: "Restock", sw: "Ongeza" },
  "product actions": { en: "Product Actions", sw: "Vitendo vya Bidhaa" },
  "are you absolutely sure?": { en: "Are you absolutely sure?", sw: "Je, una uhakika?" },
  "this will permanently delete this item.": { en: "This will permanently delete this item.", sw: "Hii itafuta bidhaa hii kabisa." },
  "product deleted successfully": { en: "Product deleted successfully", sw: "Bidhaa imefutwa" },
  "failed to delete product": { en: "Failed to delete product", sw: "Imeshindwa kufuta" },
  "in stock": { en: "in stock", sw: "zipo" },
  "select product": { en: "Select Product", sw: "Chagua Bidhaa" },
  "please fill all required fields": { en: "Please fill all required fields", sw: "Tafadhali jaza nafasi zote" },
  "shop created successfully": { en: "Shop created successfully", sw: "Duka limetengenezwa" },
  "failed to create shop": { en: "Failed to create shop", sw: "Imeshindwa kutengeneza duka" },
  "please specify the shop type": { en: "Please specify the shop type", sw: "Tafadhali taja aina ya duka" },
  "sale recorded successfully": { en: "Sale recorded successfully", sw: "Mauzo yamerekodiwa" },
  "failed to record sale": { en: "Failed to record sale", sw: "Imeshindwa kurekodi mauzo" },
  "no notifications": { en: "No notifications", sw: "Hakuna taarifa" },
  "all shops": { en: "All Shops", sw: "Maduka Yote" },
  "search products or batches...": { en: "Search products or batches...", sw: "Tafuta bidhaa..." },
  "no products match your current search/filters": { en: "No products match your current search/filters", sw: "Hakuna bidhaa" },
  "low stock": { en: "Low Stock", sw: "Stoo ni chache" },
  "no-batch": { en: "No Batch", sw: "Hakuna kundi" },
  "all": { en: "All", sw: "Zote" },
  "active": { en: "Active", sw: "Inafanya kazi" },
  "inactive": { en: "Inactive", sw: "Haifanyi kazi" },
  "loading...": { en: "Loading...", sw: "Inapakia..." },
  "success": { en: "Success", sw: "Imefanikiwa" },
  "error": { en: "Error", sw: "Hitilafu" },
  "select category": { en: "Select Category", sw: "Chagua Aina" },
  "e.g. city electronics": { en: "e.g. City Electronics", sw: "Mf. City Electronics" },
  "e.g. pharmacy": { en: "e.g. Pharmacy", sw: "Mf. Duka la Dawa" },
  "e.g. mall road, block c": { en: "e.g. Mall Road, Block C", sw: "Mf. Barabara ya Kariakoo" },
  "e.g. foundation": { en: "e.g. Foundation", sw: "Mf. Foundation" },
  "system configuration and preferences": { en: "System configuration and preferences", sw: "Mipangilio na mapendekezo ya mfumo" },
  general: { en: "General", sw: "Ujumla" },
  appearance: { en: "Appearance", sw: "Mwonekano" },
  billing: { en: "Billing", sw: "Bili" },
  alerts: { en: "Alerts", sw: "Tahadhari" },
  theme: { en: "Theme", sw: "Mandhari" },
  "system settings": { en: "System Settings", sw: "Mipangilio ya Mfumo" },
  "company name": { en: "Company Name", sw: "Jina la Kampuni" },
  "contact email": { en: "Contact Email", sw: "Barua Pepe ya Mawasiliano" },
  "maintenance mode": { en: "Maintenance Mode", sw: "Hali ya Matengenezo" },
  "temporarily disable access to the system.": { en: "Temporarily disable access to the system.", sw: "Zima ufikiaji wa mfumo kwa muda." },
  "user management": { en: "User Management", sw: "Usimamizi wa Watumiaji" },
  "manage sellers, administrators, and assign roles across your shops in the user management module.": { en: "Manage sellers, administrators, and assign roles across your shops in the user management module.", sw: "Simamia wauzaji, wasimamizi na gawa majukumu katika maduka yako." },
  "open user directory": { en: "Open User Directory", sw: "Fungua Orodha ya Watumiaji" },
  "theme & appearance": { en: "Theme & Appearance", sw: "Mandhari na Mwonekano" },
  "dark mode": { en: "Dark Mode", sw: "Hali ya Giza" },
  "toggle the application's dark mode visual theme.": { en: "Toggle the application's dark mode visual theme.", sw: "Badilisha mandhari ya giza ya programu." },
  "primary color accent": { en: "Primary Color Accent", sw: "Rangi Kuu" },
  "select theme color": { en: "Select Theme Color", sw: "Chagua Rangi ya Mandhari" },
  "blue (default)": { en: "Blue (Default)", sw: "Bluu (Kawaida)" },
  pink: { en: "Pink", sw: "Pinki" },
  emerald: { en: "Emerald", sw: "Zumaridi" },
  "shop policies & configuration": { en: "Shop Policies & Configuration", sw: "Sera na Mipangilio ya Duka" },
  "require approval for new products": { en: "Require Approval for New Products", sw: "Inahitaji idhini kwa bidhaa mpya" },
  "admins must approve products before they go live.": { en: "Admins must approve products before they go live.", sw: "Wasimamizi lazima waidhinishe bidhaa kabla ya kuonekana." },
  "allow negative inventory": { en: "Allow Negative Inventory", sw: "Ruhusu stoo hasi" },
  "permit recording sales even if stock is zero.": { en: "Permit recording sales even if stock is zero.", sw: "Ruhusu kurekodi mauzo hata kama stoo ni sifuri." },
  "enable waitlists / pre-orders": { en: "Enable Waitlists / Pre-orders", sw: "Ruhusu orodha ya kusubiri / oda za awali" },
  "customers can request items out of stock.": { en: "Customers can request items out of stock.", sw: "Wateja wanaweza kuomba bidhaa ambazo hazipo." },
  "save shop policies": { en: "Save Shop Policies", sw: "Hifadhi Sera za Duka" },
  "billing & financial settings": { en: "Billing & Financial Settings", sw: "Bili na Mipangilio ya Fedha" },
  "base currency": { en: "Base Currency", sw: "Sarafu Kuu" },
  "tanzanian shilling (tzs)": { en: "Tanzanian Shilling (TZS)", sw: "Shilingi ya Tanzania (TZS)" },
  "us dollar (usd)": { en: "US Dollar (USD)", sw: "Dola ya Marekani (USD)" },
  "kenyan shilling (kes)": { en: "Kenyan Shilling (KES)", sw: "Shilingi ya Kenya (KES)" },
  "default vat / tax rate (%)": { en: "Default VAT / Tax Rate (%)", sw: "Kiwango cha Kodi (VAT) (%)" },
  "generate invoices automatically": { en: "Generate Invoices Automatically", sw: "Tengeneza ankara moja kwa moja" },
  "create pdf receipts for every sale.": { en: "Create PDF receipts for every sale.", sw: "Tengeneza risiti za PDF kwa kila mauzo." },
  "apply financial settings": { en: "Apply Financial Settings", sw: "Tumia Mipangilio ya Fedha" },
  "notification preferences": { en: "Notification Preferences", sw: "Mapendekezo ya Taarifa" },
  "get notified when product stock falls below 10.": { en: "Get notified when product stock falls below 10.", sw: "Pata taarifa stoo ikipungua chini ya 10." },
  "daily sales summary": { en: "Daily Sales Summary", sw: "Muhtasari wa mauzo wa siku" },
  "receive an email recap of daily transactions.": { en: "Receive an email recap of daily transactions.", sw: "Pata muhtasari wa miamala ya kila siku kwa barua pepe." },
  "new device login alerts": { en: "New Device Login Alerts", sw: "Tahadhari ya kuingia kwa kifaa kipya" },
  "security alerts for unfamiliar ip logins.": { en: "Security alerts for unfamiliar IP logins.", sw: "Tahadhari za usalama kwa uingiaji usio wa kawaida." },
  "save preferences": { en: "Save Preferences", sw: "Hifadhi Mapendekezo" },
  "settings saved successfully": { en: "Settings saved successfully", sw: "Mipangilio imehifadhiwa kikamilifu" },
  "manage users, permissions & shop access": { en: "Manage users, permissions & shop access", sw: "Simamia watumiaji, ruhusa na ufikiaji wa maduka" },
  "total users": { en: "Total Users", sw: "Jumla ya Watumiaji" },
  admins: { en: "Admins", sw: "Wasimamizi" },
  sellers: { en: "Sellers", sw: "Wauzaji" },
  viewers: { en: "Viewers", sw: "Watazamaji" },
  "search users...": { en: "Search users...", sw: "Tafuta watumiaji..." },
  "full name": { en: "Full Name", sw: "Jina Kamili" },
  password: { en: "Password", sw: "Nenosiri" },
  "min 6 chars": { en: "Min 6 chars", sw: "Angalau herufi 6" },
  "admin - full access": { en: "Admin - Full access", sw: "Msimamizi - Ufikiaji kamili" },
  "seller - sales & inventory": { en: "Seller - Sales & inventory", sw: "Muuzaji - Mauzo na stoo" },
  "viewer - read only": { en: "Viewer - Read only", sw: "Mtazamaji - Kusoma tu" },
  permissions: { en: "Permissions", sw: "Ruhusa" },
  "assign shops": { en: "Assign Shops", sw: "Gawa Maduka" },
  "edit user": { en: "Edit User", sw: "Badili Mtumiaji" },
  "new password": { en: "New Password", sw: "Nenosiri Jipya" },
  "blank = unchanged": { en: "blank = unchanged", sw: "wazi = bila mabadiliko" },
  "loading users...": { en: "Loading users...", sw: "Inapakia watumiaji..." },
  "no users match your search.": { en: "No users match your search.", sw: "Hakuna watumiaji wanaendana na utafutaji." },
  "no users yet.": { en: "No users yet.", sw: "Hakuna mtumiaji bado." },
  "user created": { en: "User created", sw: "Mtumiaji ametengenezwa" },
  "failed to load data": { en: "Failed to load data", sw: "Imeshindwa kupakia data" },
  "user deleted": { en: "User deleted", sw: "Mtumiaji amefutwa" },
  "failed to delete user": { en: "Failed to delete user", sw: "Imeshindwa kufuta mtumiaji" },
  "none": { en: "None", sw: "Hakuna" },
  "user": { en: "User", sw: "Mtumiaji" },
  "delete": { en: "Delete", sw: "Futa" },
  "all associated products and sales will be removed.": { en: "All associated products and sales will be removed.", sw: "Bidhaa na mauzo yote yanayohusiana yatafutwa pia." },
  "no shops match your current search/filters": { en: "No shops match your current search/filters", sw: "Hakuna maduka yanayoendana na utafutaji wako" },
  expenses: { en: "Expenses", sw: "Matumizi" },
  "total expenses": { en: "Total Expenses", sw: "Jumla ya Matumizi" },
  "expense count": { en: "Expense Count", sw: "Idadi ya Matumizi" },
  "search expenses...": { en: "Search expenses...", sw: "Tafuta matumizi..." },
  "add expense": { en: "Add Expense", sw: "Ongeza Matumizi" },
  "record new expense": { en: "Record New Expense", sw: "Rekodi Matumizi Mapya" },
  "track your operational costs effectively": { en: "Track your operational costs effectively", sw: "Fuatilia gharama zako za uendeshaji kwa ufanisi" },
  "details about the expense...": { en: "Details about the expense...", sw: "Maelezo kuhusu matumizi haya..." },
  "record expense": { en: "Record Expense", sw: "Rekodi Matumizi" },
  "expense recorded successfully": { en: "Expense recorded successfully", sw: "Matumizi yamerekodiwa" },
  "failed to record expense": { en: "Failed to record expense", sw: "Imeshindwa kurekodi matumizi" },
  "are you sure you want to delete this expense?": { en: "Are you sure you want to delete this expense?", sw: "Je, una uhakika unataka kufuta matumizi haya?" },
  "expense deleted": { en: "Expense deleted", sw: "Matumizi yamefutwa" },
  "failed to delete expense": { en: "Failed to delete expense", sw: "Imeshindwa kufuta matumizi" },
  "no expenses found": { en: "No expenses found", sw: "Hakuna matumizi yaliyopatikana" },
  rent: { en: "Rent", sw: "Kodi ya Pango" },
  electricity: { en: "Electricity", sw: "Umeme" },
  water: { en: "Water", sw: "Maji" },
  salaries: { en: "Salaries", sw: "Mishahara" },
  maintenance: { en: "Maintenance", sw: "Matengenezo" },
  transport: { en: "Transport", sw: "Usafiri" },
  other: { en: "Other", sw: "Mengineyo" },
  "shop logo": { en: "Shop Logo", sw: "Nembo ya Duka" },
  "logo uploaded": { en: "Logo Uploaded", sw: "Nembo imepakiwa" },
  "failed to upload logo": { en: "Failed to upload logo", sw: "Imeshindwa kupakia nembo" },
  description: { en: "Description", sw: "Maelezo" },
  import: { en: "Import", sw: "Ingiza" },
  "import inventory": { en: "Import Inventory", sw: "Ingiza Stoo" },
  "import sales": { en: "Import Sales", sw: "Ingiza Mauzo" },
  "import services": { en: "Import Services", sw: "Ingiza Huduma" },
  "download template": { en: "Download Template", sw: "Pakua Kiolezo" },
  "upload an excel or csv file to bulk import inventory items": { en: "Upload an Excel or CSV file to bulk import inventory", sw: "Pakia faili ya Excel au CSV ili kuingiza stoo" },
  "upload an excel or csv file to bulk import sales items": { en: "Upload an Excel or CSV file to bulk import sales", sw: "Pakia faili ya Excel au CSV ili kuingiza mauzo" },
  "upload an excel or csv file to bulk import services items": { en: "Upload an Excel or CSV file to bulk import services", sw: "Pakia faili ya Excel au CSV ili kuingiza huduma" },
  "step 1: download template": { en: "Step 1: Download Template", sw: "Hatua ya 1: Pakua Kiolezo" },
  "step 2: upload your file": { en: "Step 2: Upload Your File", sw: "Hatua ya 2: Pakia Faili Yako" },
  "click or drag and drop file": { en: "Click or drag and drop file", sw: "Bonyeza au kokota faili hapa" },
  "xlsx, xls, csv (max 5mb)": { en: "XLSX, XLS, CSV (Max 5MB)", sw: "XLSX, XLS, CSV (Mwisho 5MB)" },
  "import now": { en: "Import Now", sw: "Ingiza Sasa" },
  "please select a specific shop from the filter to enable import.": { en: "Please select a specific shop from the filter to enable import.", sw: "Tafadhali chagua duka maalum ili kuwezesha uingizaji." },
  "imported successfully": { en: "Imported successfully", sw: "Imeingizwa kikamilifu" },
  "template downloaded": { en: "Template downloaded", sw: "Kiolezo kimepakuliwa" },
  "inventory imported successfully": { en: "Inventory imported successfully", sw: "Stoo imeingizwa kikamilifu" },
  "sales imported successfully": { en: "Sales imported successfully", sw: "Mauzo yameingizwa kikamilifu" },
  "services imported successfully": { en: "Services imported successfully", sw: "Huduma zimeingizwa kikamilifu" }
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: (localStorage.getItem("language") as Language) || "en",
  setLanguage: (lang: Language) => {
    localStorage.setItem("language", lang);
    set({ language: lang });
  },
  t: (key: string) => {
    if (!key) return "";
    const k = key.toLowerCase();
    const lang = get().language;
    return dict[k]?.[lang] || key;
  },
  formatTsh: (v: number) => `Tsh ${v?.toLocaleString() || 0}`
}));
