import { create } from "zustand";

type Language = "en" | "sw";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const dict: Record<string, { en: string; sw: string }> = {
  dashboard: { en: "Dashboard", sw: "Dashibodi" },
  shops: { en: "Shops", sw: "Maduka" },
  inventory: { en: "Inventory", sw: "Stoo" },
  sales: { en: "Sales", sw: "Mauzo" },
  services: { en: "Services", sw: "Huduma" },
  reports: { en: "Reports", sw: "Ripoti" },
  users: { en: "Users", sw: "Watumiaji" },
  settings: { en: "Settings", sw: "Mipangilio" },
  notifications: { en: "Notifications", sw: "Taarifa" },
  "audit logs": { en: "Audit Logs", sw: "Kumbukumbu (Logs)" },
  "daily summary": { en: "Daily Summary", sw: "Ripoti ya Leo" },
  "active shop": { en: "Active Shop", sw: "Duka la Sasa" },
  logout: { en: "Logout", sw: "Toka" },
  debts: { en: "Debts / Borrowing", sw: "Madeni / Kukopa" },
  "all shops (admin)": { en: "All Shops (Admin)", sw: "Maduka Yote (Admin)" },
  "all my shops": { en: "All My Shops", sw: "Maduka Yangu Yote" },
  product: { en: "Product", sw: "Bidhaa" },
  price: { en: "Price", sw: "Bei" },
  quantity: { en: "Quantity", sw: "Idadi" },
  "total amount": { en: "Total Amount", sw: "Jumla" },
  "amount paid": { en: "Amount Paid", sw: "Kiasi Kilicholipwa" },
  balance: { en: "Balance", sw: "Baki" },
  customer: { en: "Customer", sw: "Mteja" },
  save: { en: "Save", sw: "Hifadhi" },
  cancel: { en: "Cancel", sw: "Ghairi" },
  action: { en: "Action", sw: "Kitendo" },
  actions: { en: "Actions", sw: "Vitendo" },
  "add new": { en: "Add New", sw: "Ongeza Mpya" },
  "search...": { en: "Search...", sw: "Tafuta..." },
  "add product": { en: "Add Product", sw: "Ongeza Bidhaa" },
  "restock items": { en: "Restock Items", sw: "Ongeza Stoo" },
  "quick restock": { en: "Quick Restock", sw: "Ongeza Haraka" },
  "edit details": { en: "Edit Details", sw: "Badili Taarifa" },
  "delete item": { en: "Delete Item", sw: "Futa Bidhaa" },
  "product name": { en: "Product Name", sw: "Jina la Bidhaa" },
  category: { en: "Category", sw: "Aina" },
  "buying cost": { en: "Buying Cost", sw: "Gharama ya Kununua" },
  "selling price": { en: "Selling Price", sw: "Bei ya Kuuza" },
  status: { en: "Status", sw: "Hali" },
  "record sale": { en: "Record Sale", sw: "Rekodi Mauzo" },
  "sale date": { en: "Sale Date", sw: "Tarehe ya Mauzo" },
  "total cost": { en: "Total Cost", sw: "Jumla ya Gharama" },
  profit: { en: "Profit", sw: "Faida" },
  date: { en: "Date", sw: "Tarehe" },
  time: { en: "Time", sw: "Muda" },
  name: { en: "Name", sw: "Jina" },
  location: { en: "Location", sw: "Eneo" },
  role: { en: "Role", sw: "Cheo" },
  email: { en: "Email", sw: "Barua Pepe" },
  "new shop": { en: "New Shop", sw: "Duka Jipya" },
  "add user": { en: "Add User", sw: "Ongeza Mtumiaji" },
  "system overview": { en: "System Overview", sw: "Muhtasari wa Mfumo" },
  "total products": { en: "Total Products", sw: "Jumla ya Bidhaa" },
  "total sales": { en: "Total Sales", sw: "Jumla ya Mauzo" },
  "total revenue": { en: "Total Revenue", sw: "Jumla ya Mapato" },
  "inventory value": { en: "Inventory Value", sw: "Thamani ya Stoo" },
  "est. profit": { en: "Est. Profit", sw: "Faida Inayokadiriwa" },
  "critical alerts": { en: "Critical Alerts", sw: "Taarifa Muhimu" },
  "today's sales": { en: "Today's Sales", sw: "Mauzo ya Leo" },
  "today's services": { en: "Today's Services", sw: "Huduma za Leo" },
  "active inventory": { en: "Active Inventory", sw: "Stoo Inayoendelea" },
  "urgent alerts": { en: "Urgent Alerts", sw: "Maonyo ya Haraka" },
  "today's top items": { en: "Today's Top Items", sw: "Bidhaa Zinazouza Sana Leo" },
  "no transactions yet today": { en: "No transactions yet today", sw: "Hakuna miamala leo" },
  "all systems normal": { en: "All systems normal", sw: "Hakuna tatizo lolote" },
  "only": { en: "Only", sw: "Zimebaki" },
  "remaining": { en: "remaining", sw: "tu" },
  "products": { en: "Products", sw: "Bidhaa" },
  "inventory health": { en: "Inventory Health", sw: "Hali ya Stoo" },
  "stock": { en: "Stock", sw: "Stoo" },
  "healthy": { en: "Healthy", sw: "Salama" },
  "low": { en: "Low", sw: "Chini" },
  "out": { en: "Out", sw: "Zimeisha" },
  "product sales": { en: "Product Sales", sw: "Mauzo ya Bidhaa" },
  "service revenue": { en: "Service Revenue", sw: "Mapato ya Huduma" },
  "weekly performance (sales vs services)": { en: "Weekly Performance (Sales vs Services)", sw: "Uendeshaji wa Wiki" },
  "revenue source (all time)": { en: "Revenue Source (All Time)", sw: "Vyanzo vya Mapato" },
  "low stock threshold warning": { en: "Low stock threshold is set to 10 units. Consider restocking items in the 'Low' and 'Out' categories immediately.", sw: "Kiwango cha chini kimewekwa kuwa bidhaa 10. Tafadhali ongeza bidhaa zilizo chini ya kiwango hicho." },
  "items needing attention": { en: "Items needing attention", sw: "Bidhaa zinazohitaji uangalizi" },
  "today's combined": { en: "Today's combined", sw: "Jumla ya leo" },
  "today's estimate": { en: "Today's estimate", sw: "Makadirio ya leo" },
  "product sales count": { en: "Product sales count", sw: "Idadi ya mauzo ya bidhaa" },
  "unique products": { en: "Unique products", sw: "Aina za bidhaa" },
  "performance overview for": { en: "Performance Overview for", sw: "Muhtasari wa utendaji wa" },
  "manage your products and track stock levels": { en: "Manage your products and track stock levels", sw: "Simamia bidhaa na kiasi kilichopo" },
  "track daily product sales and transactions": { en: "Track daily product sales and transactions", sw: "Fuatilia mauzo na miamala ya kila siku" },
  "manage borrowing and installments": { en: "Manage borrowing and installments", sw: "Simamia mikopo na malipo ya awamu" },
  "search borrower...": { en: "Search Borrower...", sw: "Tafuta Mkopaji..." },
  "issue debt": { en: "Issue Debt", sw: "Toa Mkopo" },
  "new borrowing": { en: "New Borrowing", sw: "Kukopa Kupya" },
  "borrower name": { en: "Borrower Name", sw: "Jina la Mkopaji" },
  "phone number": { en: "Phone Number", sw: "Namba ya Simu" },
  "optional": { en: "Optional", sw: "Sio Lazima" },
  "initial paid amount": { en: "Amount Paid (Initial)", sw: "Kiasi Alicholipia Awali" },
  "due date": { en: "Due Date", sw: "Tarehe ya Mwisho" },
  "create debt": { en: "Create Debt", sw: "Tengeneza Mkopo" },
  "loading debts...": { en: "Loading debts...", sw: "Inapakia mikopo..." },
  "no borrowings found": { en: "No borrowings found", sw: "Hakuna mikopo iliyopatikana" },
  "issued": { en: "Issued", sw: "Imetolewa" },
  "due": { en: "Due", sw: "Mwisho" },
  "total": { en: "Total", sw: "Jumla" },
  "paid": { en: "Paid", sw: "Imelipwa" },
  "pay installment": { en: "Pay Installment", sw: "Lipa Awamu" },
  "shop": { en: "Shop", sw: "Duka" },
  "operational summary": { en: "Operational Summary", sw: "Muhtasari wa Utendaji" },
  "daily business metrics and stock visibility": { en: "Daily business metrics and stock visibility", sw: "Takwimu za kila siku na mwonekano wa stoo" },
  "operational status": { en: "Operational Status", sw: "Hali ya Uendeshaji" },
  "monitoring data for": { en: "Monitoring data for", sw: "Kufuatilia data kuanzia" },
  "live data": { en: "LIVE DATA", sw: "DATA SAHIHI" },
  "today's revenue": { en: "Today's Revenue", sw: "Mapato ya Leo" },
  "view sales details": { en: "View Sales details", sw: "Tazama maelezo ya Mauzo" },
  "today's profit": { en: "Today's Profit", sw: "Faida ya Leo" },
  "view profit analysis": { en: "View profit analysis", sw: "Tazama uchambuzi wa faida" },
  "current stock (total)": { en: "Current Stock (Total)", sw: "Stoo Ilipo (Jumla)" },
  "units": { en: "Units", sw: "Vipande" },
  "manage inventory": { en: "Manage inventory", sw: "Simamia stoo" },
  "inventory cost": { en: "Inventory Cost", sw: "Gharama ya Stoo" },
  "full asset valuation": { en: "Full Asset Valuation", sw: "Tathmini ya rasilimali" },
  "stock health overview": { en: "Stock Health Overview", sw: "Hali ya Afya ya Stoo" },
  "stock utilization rate": { en: "Stock Utilization Rate", sw: "Kiwango cha Matumizi ya Stoo" },
  "items monitored": { en: "Items Monitored", sw: "Bidhaa Zinazofuatiliwa" },
  "low stock alerts": { en: "Low Stock Alerts", sw: "Taarifa za Uhaba wa Stoo" },
  "performance": { en: "Performance", sw: "Utendaji" },
  "target": { en: "Target", sw: "Lengo" },
  "currently performing at 85% of today's expected operational volume.": { en: "Currently performing at 85% of today's expected operational volume.", sw: "Kwa sasa inafanya kazi kwa 85% ya kiasi cha utendaji kinachotarajiwa leo." },
  "reports & analytics": { en: "Reports & Analytics", sw: "Ripoti na Kichanganuzi" },
  "comprehensive business insights and formatted exports": { en: "Comprehensive business insights and formatted exports", sw: "Uchambuzi kamili wa biashara na ripoti" },
  "to": { en: "to", sw: "hadi" },
  "select shop": { en: "Select Shop", sw: "Chagua Duka" },
  "all available shops": { en: "All Available Shops", sw: "Maduka Yote" },
  "daily sales report": { en: "Daily Sales Report", sw: "Ripoti ya Mauzo Kubwa" },
  "detailed breakdown of product sales by date and shop.": { en: "Detailed breakdown of product sales by date and shop.", sw: "Mchanganuo wa kina wa mauzo ya bidhaa kwa tarehe na duka." },
  "services report": { en: "Services Report", sw: "Ripoti ya Huduma" },
  "summary of all services (printing, photocopying, etc).": { en: "Summary of all services (printing, photocopying, etc).", sw: "Muhtasari wa huduma zote (kuchapa, kutoa nakala, n.k)." },
  "stock health report": { en: "Stock Health Report", sw: "Ripoti ya Hali ya Stoo" },
  "inventory levels, low stock alerts, and expiring items.": { en: "Inventory levels, low stock alerts, and expiring items.", sw: "Kiwango cha stoo, alerts za chini, na bidhaa zinazokaribia kuoza." },
  "profit & loss": { en: "Profit & Loss", sw: "Faida na Hasara" },
  "analysis of revenue, costs, and net margins.": { en: "Analysis of revenue, costs, and net margins.", sw: "Uchambuzi wa mapato, gharama, na faida halisi." },
  "generating...": { en: "Generating...", sw: "Inatengeneza..." },
  "excel ai": { en: "Excel AI", sw: "Pakua Excel" },
  "creating...": { en: "Creating...", sw: "Inaunda..." },
  "pdf print": { en: "PDF Print", sw: "Pakua PDF" },
  "period revenue": { en: "Period Revenue", sw: "Mapato ya Kipindi" },
  "total profit": { en: "Total Profit", sw: "Jumla ya Faida" },
  "services cash": { en: "Services Cash", sw: "Pesa za Huduma" },
  "transactions": { en: "Transactions", sw: "Miamala" },
  "completed": { en: "Completed", sw: "Zimekamilika" },
  "asset value": { en: "Asset Value", sw: "Thamani ya Rasilimali" },
  "health alert": { en: "Health Alert", sw: "Onyo wa Hali" },
  "critical": { en: "Critical", sw: "Hatari" },
  "record new sale": { en: "Record New Sale", sw: "Rekodi Mauzo Mapya" },
  "in inventory": { en: "in inventory", sw: "stoo" },
  "adjust stock": { en: "Adjust Stock", sw: "Badili Kiasi" },
  "adjust inventory": { en: "Adjust Inventory", sw: "Badili Stoo" },
  "add, remove, or set exact stock levels": { en: "Add, remove, or set exact stock levels", sw: "Ongeza, ondoa au weka kiasi halisi" },
  "product to restock": { en: "Product to Restock", sw: "Bidhaa ya Kuongeza" },
  "type product name or batch number...": { en: "Type product name or batch number...", sw: "Andika jina la bidhaa au namba ya kundi..." },
  "no batch": { en: "No Batch", sw: "Hakuna Kundi" },
  "no matching products found": { en: "No matching products found", sw: "Hakuna bidhaa inayoendana iliyopatikana" },
  "change": { en: "Change", sw: "Badili" },
  "action type": { en: "Action Type", sw: "Aina ya Kitendo" },
  "add action": { en: "Add", sw: "Ongeza" },
  "remove action": { en: "Remove", sw: "Ondoa" },
  "set action": { en: "Set", sw: "Weka" },
  "e.g. 50": { en: "e.g. 50", sw: "Mf. 50" },
  "total after": { en: "Total after", sw: "Jumla baada ya" },
  "new batch number": { en: "New Batch Number", sw: "Namba Mpya ya Kundi" },
  "batch number": { en: "Batch Number", sw: "Namba ya Kundi" },
  "financial updates (optional)": { en: "Financial Updates (Optional)", sw: "Taarifa za Fedha (Sio Lazima)" },
  "new expiry date": { en: "New Expiry Date", sw: "Tarehe Mpya ya Kuisha Muda" },
  "updating...": { en: "Updating...", sw: "Inasisha..." },
  "confirm update": { en: "Confirm Update", sw: "Thibitisha" },
  "add service sale": { en: "Add Service Sale", sw: "Ongeza Mauzo ya Huduma" },
  "record service sale": { en: "Record Service Sale", sw: "Rekodi Mauzo ya Huduma" },
  "service name": { en: "Service Name", sw: "Jina la Huduma" },
  "price per unit": { en: "Price per Unit", sw: "Bei kwa Kipande" },
  "recording...": { en: "Recording...", sw: "Inarekodi..." },
  "record service": { en: "Record Service", sw: "Rekodi Huduma" },
  "edit": { en: "Edit", sw: "Badili" },
  "edit shop details": { en: "Edit Shop Details", sw: "Badili Taarifa za Duka" },
  "shop name": { en: "Shop Name", sw: "Jina la Duka" },
  "shop type": { en: "Shop Type", sw: "Aina ya Duka" },
  "saving...": { en: "Saving...", sw: "Inahifadhi..." },
  "save changes": { en: "Save Changes", sw: "Hifadhi Mabadiliko" },
  "create new shop": { en: "Create New Shop", sw: "Tengeneza Duka Jipya" },
  "create shop": { en: "Create Shop", sw: "Tengeneza Duka" },
  "select a shop first": { en: "Select a shop first", sw: "Chagua duka kwanza" },
  "no product found in this shop's inventory.": { en: "No product found in this shop's inventory.", sw: "Hakuna bidhaa iliyopatikana kwenye stoo ya duka hili." },
  "expiry date": { en: "Expiry date", sw: "Tarehe ya kuharibika" },
  "supplier": { en: "Supplier", sw: "Muzaji" },
  "manufacturer": { en: "Manufacturer", sw: "Mtengenezaji" },
  "adding...": { en: "Adding...", sw: "Inaongeza..." },
  "add new product": { en: "Add new product", sw: "Ongeza bidhaa mpya" },
  "barcode": { en: "Barcode", sw: "Barcode" },
  "enter quantity": { en: "Enter quantity", sw: "Weka kiasi" },
  "unit price": { en: "Unit Price", sw: "Bei ya Kipande" },
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: (localStorage.getItem("language") as Language) || "en",
  setLanguage: (lang: Language) => {
    localStorage.setItem("language", lang);
    set({ language: lang });
  },
  t: (key: string) => {
    const k = key.toLowerCase();
    const lang = get().language;
    return dict[k]?.[lang] || key;
  }
}));
